# =============================================================================
# Additive source + propagated-transmission counterfactual and legacy comparator.
#
# PRIMARY MODEL (inside one renewal recursion):
#
#   suspected S_t = true typhoid T_t + other febrile F_t
#   true typhoid T_t = exogenous/source X_t + propagated P_t
#   P_t = R_t^P * sum_s w_s T_{t-s}
#
# F_t is fixed under TCV. The source fraction theta partitions baseline
# renewal-identifiable TRUE-typhoid incidence into X_t and P_t; it does not
# average completed model outcomes. Positive incidence with Lambda_t=0 is an
# exogenous seed, irrespective of theta, because it cannot be generated by the
# renewal term.
#
# LEGACY COMPARATOR (retained only for structural comparison):
#
#   averted_weighted = theta*averted_static + (1-theta)*averted_renewal
#
# We report (a) the exact historical implementation, whose static endpoint has
# eta=0.17, and (b) a mechanism-matched eta=0 comparator. Paired differences are
# computed before summarisation.
# =============================================================================

suppressMessages({ library(dplyr); library(tidyr) })

q_num <- function(x, p) as.numeric(stats::quantile(x, p, na.rm = TRUE))

legacy_theta_weight <- function(theta, static, renewal)
  theta * static + (1 - theta) * renewal

# Frozen legacy bracket for audit/backward compatibility. This is no longer the
# primary source-decomposition result.
decompose_bracket <- function(scn, theta_tab, cfg) {
  base <- scn %>%
    filter(tau == cfg$scenario$tau_weeks,
           vacc_cov == cfg$scenario$coverage) %>%
    mutate(pct = ifelse(s_ch_tot > 0, 100 * s_ch_averted_tot / s_ch_tot, 0)) %>%
    select(study_id, draw, model, averted = s_ch_averted_tot, pct) %>%
    pivot_wider(names_from = model, values_from = c(averted, pct))
  d <- base %>%
    left_join(theta_tab[, c("study_id", "final_theta", "final_theta_lo",
                            "final_theta_hi")], by = "study_id") %>%
    filter(is.finite(final_theta)) %>%
    mutate(
      averted_theta = legacy_theta_weight(final_theta, averted_static, averted_renewal),
      averted_bound_1 =
        legacy_theta_weight(final_theta_lo, averted_static, averted_renewal),
      averted_bound_2 =
        legacy_theta_weight(final_theta_hi, averted_static, averted_renewal),
      averted_theta_lo = pmin(averted_bound_1, averted_bound_2),
      averted_theta_hi = pmax(averted_bound_1, averted_bound_2),
      pct_theta = legacy_theta_weight(final_theta, pct_static, pct_renewal))

  d %>%
    group_by(study_id) %>%
    summarise(
      final_theta = first(final_theta),
      pct_static = median(pct_static),
      pct_renewal = median(pct_renewal),
      pct_theta = median(pct_theta),
      averted_static = median(averted_static),
      averted_renewal = median(averted_renewal),
      averted_theta = median(averted_theta),
      averted_theta_lo = median(averted_theta_lo),
      averted_theta_hi = median(averted_theta_hi),
      averted_theta_p025 = q_num(averted_theta, 0.025),
      averted_theta_p975 = q_num(averted_theta, 0.975),
      .groups = "drop")
}

# Algebraic validation of the frozen historical outcome-weighting formula.
validate_legacy_endpoints <- function(scn, cfg) {
  base <- scn %>%
    filter(tau == cfg$scenario$tau_weeks,
           vacc_cov == cfg$scenario$coverage) %>%
    select(study_id, draw, model, averted = s_ch_averted_tot) %>%
    pivot_wider(names_from = model, values_from = averted)
  blend <- function(th) legacy_theta_weight(th, base$static, base$renewal)
  c(
    err_theta1_vs_static =
      max(abs(blend(1) - base$static), na.rm = TRUE),
    err_theta0_vs_renewal =
      max(abs(blend(0) - base$renewal), na.rm = TRUE)
  )
}

# Cross-validate Stream A (paper) and Stream B (data) -> final theta + agreement.
cross_validate <- function(streamA, streamB) {
  a <- streamA %>% mutate(theta_paper = (theta_paper_lo + theta_paper_hi) / 2)
  a %>%
    left_join(streamB, by = "study_id") %>%
    mutate(
      agreement = ifelse(
        is.finite(theta_data) & abs(theta_paper - theta_data) <= 0.2,
        "agree", "disagree"),
      # Paper evidence is primary. Curve-shape evidence only widens the
      # structural range because the source fraction is not identified from a
      # single incidence curve.
      final_theta = theta_paper,
      final_theta_lo = pmin(
        theta_paper_lo,
        ifelse(is.finite(theta_data), theta_data, theta_paper_lo)),
      final_theta_hi = pmax(
        theta_paper_hi,
        ifelse(is.finite(theta_data), theta_data, theta_paper_hi)))
}

# Run the two-level additive model and both theta-weighted comparators with
# identical PPV, Sobol, efficacy, timing, coverage, GI, and theta inputs.
simulate_source_comparison <- function(
    prep, rcfg, theta_tab, cfg, pi_post = NULL,
    tau = cfg$scenario$tau_weeks,
    coverage = cfg$scenario$coverage) {
  w <- gi_from_config(rcfg)
  params <- build_param_sets(rcfg)
  ndraw <- nrow(params)
  study_ids <- intersect(names(prep$series), theta_tab$study_id)
  if (!length(study_ids)) stop("No source-classified renewal outbreaks found")

  pim <- if (is.null(pi_post)) {
    matrix(1, nrow = ndraw, ncol = length(study_ids),
           dimnames = list(NULL, study_ids))
  } else {
    build_pi_matrix(
      pi_post, study_ids, ndraw, seed = rcfg$seed + 777L)
  }

  rows <- vector("list", length(study_ids) * ndraw)
  k <- 0L
  for (sid in study_ids) {
    S <- as.numeric(prep$series[[sid]])
    Tn <- length(S)
    th <- theta_tab[match(sid, theta_tab$study_id), ]
    theta <- th$final_theta
    theta_lo <- th$final_theta_lo
    theta_hi <- th$final_theta_hi
    if (any(!is.finite(c(theta, theta_lo, theta_hi))))
      stop("Missing source fraction for ", sid)
    tail_guard <- Tn - rcfg$tail_guard_weeks

    for (i in seq_len(ndraw)) {
      psi <- params$dve[i]
      # Base-case source comparison uses psi_T=psi. The separate psi_T
      # sensitivity remains in renewal/run_analysis.R.
      psi_T <- psi
      te <- t_eff_weeks(
        tau, params$immuno_delay[i], params$campaign_duration[i],
        rcfg$step_days)
      te_int <- max(round(te), 1L)
      occurred <- te <= tail_guard

      obs <- ppv_incidence_components(S, pim[i, sid])
      T <- obs$true_typhoid
      F <- obs$other_febrile
      c_t <- protected_fraction(
        Tn, tau, te_int, rcfg$timing$c_shape)

      add_point <- additive_source_counterfactual(
        T, w, tau, te_int, coverage, psi_T, theta,
        c_shape = rcfg$timing$c_shape)
      add_lo <- additive_source_counterfactual(
        T, w, tau, te_int, coverage, psi_T, theta_lo,
        c_shape = rcfg$timing$c_shape)
      add_hi <- additive_source_counterfactual(
        T, w, tau, te_int, coverage, psi_T, theta_hi,
        c_shape = rcfg$timing$c_shape)
      # theta=0 with the same exogenous-seed policy is the mechanism-matched
      # pure-renewal endpoint.
      ren_matched <- additive_source_counterfactual(
        T, w, tau, te_int, coverage, psi_T, 0,
        c_shape = rcfg$timing$c_shape)
      add_theta1 <- additive_source_counterfactual(
        T, w, tau, te_int, coverage, psi_T, 1,
        c_shape = rcfg$timing$c_shape)
      # Exact historical renewal implementation retained for comparison.
      ren_historical <- renewal_counterfactual(
        T, w, tau, te_int, coverage, psi_T,
        c_shape = rcfg$timing$c_shape, feedback = TRUE)
      direct_cf <- static_counterfactual(
        T, te_int, P_halloran(coverage, psi, eta = 0), c_t = c_t)
      historical_static_cf <- static_counterfactual(
        T, te_int,
        P_halloran(coverage, psi, eta = rcfg$vaccine$eta_static),
        c_t = c_t)

      averted <- function(v) if (occurred)
        impact_measures(T, v)$averted else 0
      a_add <- averted(add_point$incidence_v)
      a_add_lo <- averted(add_lo$incidence_v)
      a_add_hi <- averted(add_hi$incidence_v)
      a_ren_matched <- averted(ren_matched$incidence_v)
      a_ren_historical <- averted(ren_historical$incidence_v)
      a_direct <- averted(direct_cf)
      a_static_historical <- averted(historical_static_cf)
      a_weighted_matched <-
        legacy_theta_weight(theta, a_direct, a_ren_matched)
      a_weighted_historical <-
        legacy_theta_weight(
          theta, a_static_historical, a_ren_historical)
      true_total <- sum(T)
      suspected_total <- sum(S)
      pct_true <- function(a) if (true_total > 0) 100 * a / true_total else 0
      pct_observed <- function(a)
        if (suspected_total > 0) 100 * a / suspected_total else 0

      k <- k + 1L
      rows[[k]] <- data.frame(
        study_id = sid,
        draw = i,
        tau = tau,
        vacc_cov = coverage,
        theta = theta,
        theta_lo = theta_lo,
        theta_hi = theta_hi,
        theta_realized = add_point$source_fraction_realized,
        pi_ppv = pim[i, sid],
        psi = psi,
        psi_T = psi_T,
        t_eff = te_int,
        ori_occurred = occurred,
        suspected_total = suspected_total,
        true_typhoid_total = true_total,
        other_febrile_total = sum(F),
        source_typhoid_total = sum(add_point$source_obs),
        propagated_typhoid_total = sum(add_point$propagated_obs),
        averted_additive = a_add,
        averted_additive_theta_lo = a_add_lo,
        averted_additive_theta_hi = a_add_hi,
        averted_renewal_matched = a_ren_matched,
        averted_renewal_historical = a_ren_historical,
        averted_direct = a_direct,
        averted_static_historical = a_static_historical,
        averted_theta_weighted_matched = a_weighted_matched,
        averted_theta_weighted_historical = a_weighted_historical,
        true_pct_additive = pct_true(a_add),
        true_pct_additive_theta_lo = pct_true(a_add_lo),
        true_pct_additive_theta_hi = pct_true(a_add_hi),
        true_pct_theta_weighted_matched = pct_true(a_weighted_matched),
        true_pct_theta_weighted_historical =
          pct_true(a_weighted_historical),
        observed_pct_additive = pct_observed(a_add),
        observed_pct_theta_weighted_historical =
          pct_observed(a_weighted_historical),
        delta_cases_vs_historical = a_add - a_weighted_historical,
        delta_true_pp_vs_historical =
          pct_true(a_add) - pct_true(a_weighted_historical),
        delta_observed_pp_vs_historical =
          pct_observed(a_add) - pct_observed(a_weighted_historical),
        delta_cases_vs_matched = a_add - a_weighted_matched,
        delta_true_pp_vs_matched =
          pct_true(a_add) - pct_true(a_weighted_matched),
        observation_balance_error = obs$mass_balance_error,
        ppv_error = obs$ppv_error,
        baseline_balance_error = add_point$baseline_error,
        counterfactual_balance_error =
          add_point$counterfactual_balance_error,
        theta1_endpoint_error =
          max(abs(add_theta1$incidence_v - direct_cf)),
        max_counterfactual_excess =
          max(add_point$incidence_v - T),
        min_component = min(
          F, add_point$source_obs, add_point$propagated_obs,
          add_point$source_v, add_point$propagated_v),
        legacy_formula_error = abs(
          a_weighted_historical -
            legacy_theta_weight(
              theta, a_static_historical, a_ren_historical)),
        matched_formula_error = abs(
          a_weighted_matched -
            legacy_theta_weight(theta, a_direct, a_ren_matched)),
        stringsAsFactors = FALSE)
    }
  }
  bind_rows(rows[seq_len(k)])
}

summarise_source_comparison <- function(draws) {
  draws %>%
    mutate(
      additive_structural_lo = pmin(
        true_pct_additive_theta_lo, true_pct_additive_theta_hi),
      additive_structural_hi = pmax(
        true_pct_additive_theta_lo, true_pct_additive_theta_hi)) %>%
    group_by(study_id) %>%
    summarise(
      theta = first(theta),
      theta_lo = first(theta_lo),
      theta_hi = first(theta_hi),
      theta_realized_median = median(theta_realized),
      ppv_median = median(pi_ppv),
      suspected_total = first(suspected_total),
      true_typhoid_total_median = median(true_typhoid_total),
      pct_additive_median = median(true_pct_additive),
      pct_additive_p025 = q_num(true_pct_additive, 0.025),
      pct_additive_p975 = q_num(true_pct_additive, 0.975),
      pct_additive_structural_lo = median(additive_structural_lo),
      pct_additive_structural_hi = median(additive_structural_hi),
      pct_theta_weighted_historical_median =
        median(true_pct_theta_weighted_historical),
      pct_theta_weighted_historical_p025 =
        q_num(true_pct_theta_weighted_historical, 0.025),
      pct_theta_weighted_historical_p975 =
        q_num(true_pct_theta_weighted_historical, 0.975),
      pct_theta_weighted_matched_median =
        median(true_pct_theta_weighted_matched),
      averted_additive_median = median(averted_additive),
      averted_theta_weighted_historical_median =
        median(averted_theta_weighted_historical),
      delta_cases_vs_historical_median =
        median(delta_cases_vs_historical),
      delta_cases_vs_historical_p025 =
        q_num(delta_cases_vs_historical, 0.025),
      delta_cases_vs_historical_p975 =
        q_num(delta_cases_vs_historical, 0.975),
      delta_true_pp_vs_historical_median =
        median(delta_true_pp_vs_historical),
      delta_true_pp_vs_historical_p025 =
        q_num(delta_true_pp_vs_historical, 0.025),
      delta_true_pp_vs_historical_p975 =
        q_num(delta_true_pp_vs_historical, 0.975),
      delta_true_pp_vs_matched_median =
        median(delta_true_pp_vs_matched),
      observed_pct_additive_median =
        median(observed_pct_additive),
      observed_pct_theta_weighted_historical_median =
        median(observed_pct_theta_weighted_historical),
      .groups = "drop")
}

summarise_pooled_source_comparison <- function(draws) {
  pooled <- draws %>%
    group_by(draw) %>%
    summarise(
      suspected_total = sum(suspected_total),
      true_typhoid_total = sum(true_typhoid_total),
      additive = sum(averted_additive),
      historical = sum(averted_theta_weighted_historical),
      matched = sum(averted_theta_weighted_matched),
      .groups = "drop") %>%
    mutate(
      delta_cases = additive - historical,
      additive_true_pct = 100 * additive / true_typhoid_total,
      historical_true_pct = 100 * historical / true_typhoid_total,
      matched_true_pct = 100 * matched / true_typhoid_total,
      delta_true_pp = additive_true_pct - historical_true_pct,
      delta_matched_pp = additive_true_pct - matched_true_pct,
      additive_observed_pct = 100 * additive / suspected_total,
      historical_observed_pct = 100 * historical / suspected_total,
      delta_observed_pp =
        additive_observed_pct - historical_observed_pct)
  med <- function(x) median(x, na.rm = TRUE)
  lo <- function(x) q_num(x, 0.025)
  hi <- function(x) q_num(x, 0.975)
  data.frame(
    n_outbreaks = length(unique(draws$study_id)),
    additive_cases_median = med(pooled$additive),
    additive_cases_p025 = lo(pooled$additive),
    additive_cases_p975 = hi(pooled$additive),
    historical_weighted_cases_median = med(pooled$historical),
    historical_weighted_cases_p025 = lo(pooled$historical),
    historical_weighted_cases_p975 = hi(pooled$historical),
    delta_cases_median = med(pooled$delta_cases),
    delta_cases_p025 = lo(pooled$delta_cases),
    delta_cases_p975 = hi(pooled$delta_cases),
    additive_true_pct_median = med(pooled$additive_true_pct),
    historical_weighted_true_pct_median =
      med(pooled$historical_true_pct),
    matched_weighted_true_pct_median = med(pooled$matched_true_pct),
    delta_true_pp_median = med(pooled$delta_true_pp),
    delta_true_pp_p025 = lo(pooled$delta_true_pp),
    delta_true_pp_p975 = hi(pooled$delta_true_pp),
    delta_vs_matched_pp_median = med(pooled$delta_matched_pp),
    additive_observed_pct_median =
      med(pooled$additive_observed_pct),
    historical_weighted_observed_pct_median =
      med(pooled$historical_observed_pct),
    delta_observed_pp_median = med(pooled$delta_observed_pp),
    stringsAsFactors = FALSE)
}

source_validation_table <- function(draws, tolerance = 1e-8) {
  key <- paste(
    draws$study_id, draws$draw, draws$tau, draws$vacc_cov, sep = "|")
  metrics <- c(
    observation_mass_balance =
      max(draws$observation_balance_error),
    cumulative_ppv =
      max(draws$ppv_error),
    transmission_baseline_mass_balance =
      max(draws$baseline_balance_error),
    transmission_counterfactual_mass_balance =
      max(draws$counterfactual_balance_error),
    theta1_direct_endpoint =
      max(draws$theta1_endpoint_error),
    counterfactual_not_above_baseline =
      max(0, max(draws$max_counterfactual_excess)),
    nonnegative_components =
      max(0, -min(draws$min_component)),
    historical_weight_formula =
      max(draws$legacy_formula_error),
    matched_weight_formula =
      max(draws$matched_formula_error),
    duplicate_paired_keys =
      sum(duplicated(key)))
  data.frame(
    check = names(metrics),
    value = as.numeric(metrics),
    tolerance = tolerance,
    pass = as.numeric(metrics) <= tolerance,
    stringsAsFactors = FALSE)
}
