# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

seiarw <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw`, params)
}

seiarw_2ag_erlang <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw_2ag_erlang`, params)
}

seiarw_2ag_erlang_vacc_simple <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw_2ag_erlang_vacc_simple`, params)
}

seiarw_2ag_erlang_vacc <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw_2ag_erlang_vacc`, params)
}

seiarw_check <- function(params) {
    .Call(`_CholeraOutbreakModel_seiarw_check`, params)
}

